name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: PortfolioWeb/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: PortfolioWeb

      - name: Build project
        run: CI=false npm run build
        working-directory: PortfolioWeb

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: PortfolioWeb/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Mantido por segurança, caso seja necessário para metadados ou futuros comandos do Netlify CLI

      - name: Verify netlify.toml presence
        run: |
          echo "Listing files in current directory (root of repo):"
          ls -la .
          echo "Content of netlify.toml (if found):"
          cat netlify.toml || echo "netlify.toml not found or empty."
          echo "Current working directory:"
          pwd

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build # Os ficheiros serão baixados para o diretório 'build' na raiz do runner

      - name: Show build output
        run: ls -la build # Útil para depurar e confirmar que os ficheiros estão lá

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        # Este comando está correto. O problema era a ausência do netlify.toml que guia o Netlify
        # para não tentar adivinhar o build.
        run: netlify deploy --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }} --prod --dir=build
