# netlify.toml
[build]
  publish = "Portfolio-master/build"  # Diz ao Netlify que a pasta a servir é Portfolio-master/build
  command = "# npm run build"         # Comenta o comando de build para o Netlify não tentar construí-lo